#!/usr/bin/env python

import os
import json
#import yaml
#from ed_helper_publisher.utilities import print_json

terraform_state_file = os.environ.get("TERRAFORM_STATE_FILE","terraform.tfstate")
ed_resources_file = os.environ.get("ED_RESOURCES_FILE","ed_resources.json")

with open(terraform_state_file) as json_file:
    data = json.load(json_file)

with open(terraform_state_file) as json_file:
    raw = json.load(json_file)

if not data:
    print "ERROR - there is no data from {}".format(os.path.join(os.getcwd(),terraform_state_file))
    exit(9)

ed_resources = []
_results = {}

# get the ssh key information
for resource in data["resources"]:

    if resource.get("type") not in [ "aws_key_pair", "tls_private_key" ]: continue
    instance = resource["instances"][0]
 
    if resource.get("type") == "aws_key_pair":
        _results["name"] = instance["attributes"]["key_name"]
        continue

    for _key,_value in instance["attributes"].iteritems():
        _results[_key] = _value

    _results["private_key"] = instance["attributes"]["private_key_pem"]
    _results["public_key"] = instance["attributes"]["public_key_openssh"]
    _results["provider"] = "aws"
    _results["resource_type"] = "ssh_key_pair"
    _results["main"] = True
    _results["raw"] = {"terraform":raw}

ed_resources.append(_results)

# get the servers/instances information
for resource in data["resources"]:
    for instance in resource["instances"]:

        _rtype = resource["type"]
        if _rtype != "aws_instance": continue

        _results = {}

        for _key,_value in instance["attributes"].iteritems():
            _results[_key] = _value

        _results["_id"] = instance["attributes"]["id"]
        _results["ami"] = instance["attributes"]["ami"]
        _results["arn"] = instance["attributes"]["arn"]
        
        _results["private_dns"] = instance["attributes"]["private_dns"]
        _results["private_ip"] = instance["attributes"]["private_ip"]
        
        if instance["attributes"].get("public_dns"):
            _results["public_dns"] = instance["attributes"]["public_dns"]
        
        if instance["attributes"].get("public_ip"):
            _results["public_ip"] = instance["attributes"]["public_ip"]

        _results["name"] = _results["tags"]["Name"]
        _results["provider"] = "aws"
        _results["region"] = _results["arn"].split(":")[3]
        _results["raw"] = {"terraform":raw}
        _results["resource_type"] = "server"
        ed_resources.append(_results)

# write resources to output file
with open(ed_resources_file,'w') as outfile:
    json.dump(ed_resources,outfile)

#with open(ed_resources_file) as json_file:
#    data = json.load(json_file)
#
#print_json(data)

#with open(ed_resources_file, 'w') as yaml_file:
#    yaml_file.write(yaml.safe_dump(ed_resources,default_flow_style=False))

#print '_ed_begin_output'
#print_json(ed_resources)
#print '_ed_end_output'
