#!/usr/bin/env python

import sys

from ed_helper_publisher.loggerly import ElasticDevLogger
from ed_helper_publisher.resource_manage import ResourceCmdHelper

class Main(ResourceCmdHelper):

    def __init__(self,**kwargs):

        ResourceCmdHelper.__init__(self,app_name="ansible",must_exists=["stateful_id"])

        self.classname = 'ANSIBLE_PRIVATE_KEY'
        self.logger = ElasticDevLogger(self.classname,logcategory="cloudprovider")
        self.logger.debug("Instantiating %s" % self.classname)

        set_env_vars = [ "ANS_VAR_private_key",
                         "ANSIBLE_DIR",
                         "method" ]

        self.set_inputargs(set_env_vars=set_env_vars,upper_case=None)

        # if you want to remap vars for the application in the inputargs
        # e.g. ANS_VAR_mongodb_public_ips to mongodb_public_ips
        self.remap_app_vars()

    def create(self):

        filepath = "{}/ssh_key.pem".format(self.exec_dir)

        self.write_key_to_file(key="private_key",
                               filepath=filepath,
                               split_char="return",
                               deserialize=True,
                               add_return=True,
                               permission=400)

def usage():

    print """
script + environmental variables

or

script + json_input (as argument)

environmental variables:

    create:
        ANSIBLE_DIR
        ANS_VAR_private_key
        method

       """
    exit(4)

if __name__ == '__main__':

    try:
        json_input = sys.argv[1]
    except:
        json_input = None

    main = Main()

    if main.inputargs.get("method","create") == "create":

        main.check_required_inputargs(keys=["private_key"])
        main.create()

    else:
        usage()
        print 'method "{}" not supported!'.format(main.inputargs.get("method","create"))
        exit(4)
