#!/usr/bin/env python

import os

layer = os.environ["EXECUTION_LAYER"]

version = os.environ.get("HELLO_VERSION")
if not version: version = 1

store_file = os.environ.get("STORE_FILE")
if not store_file: store_file = "/tmp/{}.txt".format(version)

statement = "hello world {} at execution layer".format(version,layer)

print("#"*32)
print("")
print("hello world script another version")
print("hello world script another version")
print("hello world script another version")
print("hello world script another version")
print("")
print(statement)
print("")
print("#"*32)

with open(store_file,"w") as f:
    f.write(statement)

