#!/usr/bin/env python

import os

env_file = os.environ.get("ENV_FILE")
if not env_file: env_file = os.environ.get("DOCKER_ENV_FILE","/var/tmp/docker/build/.env")

base_dir = os.environ.get("BASE_DIR",os.getcwd())
cluster_vars_dir = "cluster_vars"

cluster_vars_fqn_dir = "{}/{}".format(base_dir,cluster_vars_dir)

if not os.path.isdir(cluster_vars_fqn_dir): 
    print "cluster_vars directory does not exists"
    exit(0)

env_files = sorted([f for f in os.listdir(cluster_vars_fqn_dir) if f.endswith('.env')])

if not env_files:
    print "cluster_vars directory is empty"
    exit(0)

if ".env" in env_files: 
    env_files.remove(".env")
    env_files.append(".env")

env_file_handle = open(env_file,"wb")

with open(env_file,'w') as env_file_handle:
    for _file in env_files:
        lines = open("{}/{}".format(cluster_vars_fqn_dir,_file),"r")
        for line in lines:
            line = line.strip()
            if not line: continue
            if line.startswith("#"): continue
            env_file_handle.write("{}\n".format(line))
    
