#!/usr/bin/env python

import os

build_dir = os.environ.get("DOCKER_BUILD_DIR","/var/tmp/docker/build")
env_file_path = "{}/.env".format(build_dir)

contents = list(open(env_file_path,'rb').read().split("\n"))

node_env = os.environ.get("NODE_ENV","staging")
meteor_settings = os.environ.get("METEOR_SETTINGS",'{}')
mail_url = os.environ.get("MAIL_URL")
app_bundle_dir = os.environ.get("APP_BUNDLE_DIR","/opt/meteor/dist/bundle")
app_user = os.environ.get("APP_USER","node")
app_startup_file = os.environ.get("APP_STARTUP_FILE","main.js")
mongo_host = os.environ.get("MONGO_HOST","127.0.0.1")

deploy_soa = os.environ.get("DeploySOA")
deploy_color = os.environ.get("DeployColor")

root_url = "http://127.0.0.1"
if deploy_soa and deploy_color: root_url = "http://{}.{}".format(deploy_color,deploy_soa)

mongo_oplog_url = 'mongodb://{}:27017/local'.format(mongo_host)

key_checks = []
key_checks.append("node_env")
key_checks.append("meteor_settings")
key_checks.append("mail_url")
key_checks.append("app_bundle_dir")
key_checks.append("app_user")
key_checks.append("app_startup_file")
key_checks.append("mongo_host")

key_checks.append("root_url")

##########################################
#revisit729
#seems like the oplog causese duplication issues
#removing for now
#key_checks.append("mongo_oplog_url")
##########################################

#########################

def check_key(key,contents):

    for line in contents:
        match = "{}=".format(key.upper())
        if match in line: return True
    
    return 

#########################

key_adds = []

for key in key_checks:

    if check_key(key,contents): continue
    key_adds.append(key)

#########################

if key_adds:
   for key in key_adds:
       add_value = "{}={}".format(key.upper(),eval(key))
       contents.append(add_value)

   #Write the entire file over again
   writefile = open(env_file_path,"wb")
   for line in contents:
       if not line: continue
       writefile.write(line)
       writefile.write("\n")
   writefile.close()
